version: "3.10"

x-postgres-environment: &x-postgres-environment
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_NAME: ${POSTGRES_NAME}

services:
  database:
    restart: always
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      <<: *x-postgres-environment

  backend:
    build: backend
    restart: always
    volumes:
      - ./backend/app/:/application/
    environment:
      <<: *x-postgres-environment
    ports:
      - "3000:8000"

volumes:
  pgdata: